"""create initial tables

Revision ID: 73c6db1e2ae3
Revises: 
Create Date: 2024-11-27 06:30:26.093965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c6db1e2ae3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('ai_model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ai_model_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('ai_model_id'),
    sa.UniqueConstraint('ai_model_name')
    )
    op.create_index(op.f('ix_ai_models_ai_model_id'), 'ai_models', ['ai_model_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('user_icon', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('default_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_model_id'], ['ai_models.ai_model_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=False),
    sa.Column('use_model_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['use_model_id'], ['ai_models.ai_model_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=False)
    op.create_index('ix_chats_user_id_created_at', 'chats', ['user_id', 'created_at'], unique=False)
    op.create_table('dictionaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionaries_id'), 'dictionaries', ['id'], unique=False)
    op.create_index(op.f('ix_dictionaries_term'), 'dictionaries', ['term'], unique=False)
    op.create_index(op.f('ix_dictionaries_user_id'), 'dictionaries', ['user_id'], unique=False)
    op.create_index('ix_term_user_id', 'dictionaries', ['term', 'user_id'], unique=True)
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('sender_type', sa.Enum('user', 'ai', name='sender_type'), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_messages_chat_id_created_at', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    # ### end Alembic commands ###

    # # 初期データの投入を追加（最後に追加）
    # op.execute("""
    #     INSERT INTO ai_models (ai_model_id, ai_model_name, description) 
    #     VALUES 
    #         (1, 'GPT-3.5-turbo', 'OpenAI GPT-3.5モデル'),
    #         (2, 'GPT-4o', 'OpenAI GPT-4モデル'),
    #         (3, 'Claude-3-5-sonnet', 'Anthropic Claudeモデル')
    #     ON DUPLICATE KEY UPDATE
    #         ai_model_name = VALUES(ai_model_name),
    #         description = VALUES(description)
    # """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index('ix_messages_chat_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_term_user_id', table_name='dictionaries')
    op.drop_index(op.f('ix_dictionaries_user_id'), table_name='dictionaries')
    op.drop_index(op.f('ix_dictionaries_term'), table_name='dictionaries')
    op.drop_index(op.f('ix_dictionaries_id'), table_name='dictionaries')
    op.drop_table('dictionaries')
    op.drop_index('ix_chats_user_id_created_at', table_name='chats')
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ai_models_ai_model_id'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
